
save(stocks, file = "Data/stocks.Rdata")
save(allstocks, file = "Data/allstocks.Rdata") 

save(HARmeasures, file = "Data/HARmeasures.Rdata") 

save(AR1_RV_fit, file = "Data/AR1_RV_fit.Rdata") 
save(ARMAGARCH_fit, file = "Data/ARMAGARCH_fit.Rdata") 
save(HAR_fit, file = "Data/HAR_fit.Rdata") 
save(HARAS_fit, file = "Data/HARAS_fit.Rdata") 
save(HARS_fit, file = "Data/HARS_fit.Rdata") 
save(HARS_fit, file = "Data/HARSK_fit.Rdata") 
save(RGARCH_fit, file = "Data/RGARCH_fit.Rdata") 

save(RGARCH, file = "Data/RGARCH.Rdata")
save(ARMAGARCH, file = "Data/ARMAGARCH.Rdata")

save(pre_covid_end_date, file = "Data/pre_covid_end_date.Rdata")
save(forecast_start_date, file = "Data/forecast_start_date.Rdata")
save(minimum_length, file = "Data/minimum_length.Rdata")
save(n_for, file = "Data/n_for.Rdata")
save(max_possible_date_diff, file = "Data/max_possible_date_diff.Rdata")

save(stocks, file = "Data/stocks.Rdata")  
save(allstocks, file = "Data/allstocks.Rdata")  
save(HARmeasures, file = "Data/HARmeasures.Rdata")

save(data_aux, file = "Data/data_aux.Rdata") 
save(TT, file = "Data/TT.Rdata") 
save(RV_5, file = "Data/RV_5.Rdata") 
save(RV_22, file = "Data/RV_22.Rdata") 
save(T_5, file = "Data/T_5.Rdata") 
save(T_22, file = "Data/T_22.Rdata") 
save(HAR_DATA, file = "Data/HAR_DATA.Rdata") 
save(true_vals, file = "Data/true_vals.Rdata") 

save(AR1_RV_fc_e_er, file = "Data/AR1_RV_fc_e_er.Rdata")
save(AR1_RV_fc_r_er, file = "Data/AR1_RV_fc_r_er.Rdata")
save(HAR_fc_e_er, file = "Data/HAR_fc_e_er.Rdata")
save(HAR_fc_r_er, file = "Data/HAR_fc_r_er.Rdata")  
save(HAR_AS_fc_e_er, file = "Data/HAR_AS_fc_e_er.Rdata")
save(HAR_AS_fc_r_er, file = "Data/HAR_AS_fc_r_er.Rdata")
save(HAR_RSV_fc_e_er, file = "Data/HAR_RSV_fc_e_er.Rdata")
save(HAR_RSV_fc_r_er, file = "Data/HAR_RSV_fc_r_er.Rdata")  
save(HAR_RSRK_fc_e_er, file = "Data/HAR_RSRK_fc_e_er.Rdata")
save(HAR_RSRK_fc_r_er, file = "Data/HAR_RSRK_fc_r_er.Rdata")
save(RGARCH_fc_e_er, file = "Data/RGARCH_fc_e_er.Rdata")
save(RGARCH_fc_r_er, file = "Data/RGARCH_fc_r_er.Rdata")  
save(ARMAGARCH_fc_e_er, file = "Data/ARMAGARCH_fc_e_er.Rdata")
save(ARMAGARCH_fc_r_er, file = "Data/ARMAGARCH_fc_r_er.Rdata")

save(errs, file = "Data/errs.Rdata")

save(MSE_e, file = "Data/MSE_e.Rdata")
save(MSE_r, file = "Data/MSE_r.Rdata")
save(MSEs, file = "Data/MSEs.Rdata")
save(MAE_e, file = "Data/MAE_e.Rdata")
save(MAE_r, file = "Data/MAE_r.Rdata")
save(MAEs, file = "Data/MAEs.Rdata")

save(Exp_comb , file = "Data/Exp_comb.Rdata")
save(Roll_comb, file = "Data/Roll_comb.Rdata")
save(Diebold_e, file = "Data/Diebold_e.Rdata")
save(Diebold_r, file = "Data/Diebold_r.Rdata")

save(regressions , file = "Data/regressions.Rdata")
save(Minc_AR1_RV_e , file = "Data/Minc_AR1_RV_e.Rdata")
save(Minc_AR1_RV_r , file = "Data/Minc_AR1_RV_r .Rdata")
save(Minc_HAR_e , file = "Data/Minc_HAR_e.Rdata")
save(Minc_HAR_r , file = "Data/Minc_HAR_r.Rdata")
save(Minc_HAR_AS_e , file = "Data/Minc_HAR_AS_e.Rdata")
save(Minc_HAR_AS_r , file = "Data/Minc_HAR_AS_r.Rdata")
save(Minc_HAR_RS_e , file = "Data/Minc_HAR_RS_e.Rdata")
save(Minc_HAR_RS_r , file = "Data/Minc_HAR_RS_r.Rdata")
save(Minc_HAR_RSRK_e , file = "Data/Minc_HAR_RSRK_e.Rdata")
save(Minc_HAR_RSRK_r , file = "Data/Minc_HAR_RSRK_r.Rdata")
save(Minc_RGARCH_e , file = "Data/Minc_RGARCH_e.Rdata")
save(Minc_RGARCH_r , file = "Data/Minc_RGARCH_r.Rdata")
save(Minc_ARMAGARCH_e , file = "Data/Minc_ARMAGARCH_e.Rdata")
save(Minc_ARMAGARCH_r , file = "Data/Minc_ARMAGARCH_r.Rdata")
save(mincer , file = "Data/mincer.Rdata")

save(VaR95_AR1_RV_e, file = "Data/VaR95_AR1_RV_e.Rdata")
save(VaR95_AR1_RV_r, file = "Data/VaR95_AR1_RV_r.Rdata")
save(VaR95_HAR_e, file = "Data/VaR95_HAR_e.Rdata")
save(VaR95_HAR_r, file = "Data/VaR95_HAR_r.Rdata")
save(VaR95_HAR_AS_e, file = "Data/VaR95_HAR_AS_e.Rdata")
save(VaR95_HAR_AS_r, file = "Data/VaR95_HAR_AS_r.Rdata")
save(VaR95_HAR_RSV_e, file = "Data/VaR95_HAR_RSV_e.Rdata")
save(VaR95_HAR_RSV_r, file = "Data/VaR95_HAR_RSV_r.Rdata")
save(VaR95_HAR_RSRK_e, file = "Data/VaR95_HAR_RSRK_e.Rdata")
save(VaR95_HAR_RSRK_r, file = "Data/VaR95_HAR_RSRK_r.Rdata")
save(VaR95_RGARCH_e, file = "Data/VaR95_RGARCH_e.Rdata")
save(VaR95_RGARCH_r, file = "Data/VaR95_RGARCH_r.Rdata")
save(VaR95_ARMAGARCH_e, file = "Data/VaR95_ARMAGARCH_e.Rdata")
save(VaR95_ARMAGARCH_r, file = "Data/VaR95_ARMAGARCH_r.Rdata")

save(Backtests_AR1_RV_e, file = "Data/Backtests_AR1_RV_e.Rdata")
save(Backtests_AR1_RV_r, file = "Data/Backtests_AR1_RV_r.Rdata")
save(Backtests_HAR_e, file = "Data/Backtests_HAR_e.Rdata")
save(Backtests_HAR_r, file = "Data/Backtests_HAR_r.Rdata")
save(Backtests_HAR_AS_e, file = "Data/Backtests_HAR_AS_e.Rdata")
save(Backtests_HAR_AS_r, file = "Data/Backtests_HAR_AS_r.Rdata")
save(Backtests_HAR_RS_e, file = "Data/Backtests_HAR_RS_e.Rdata")
save(Backtests_HAR_RS_r, file = "Data/Backtests_HAR_RS_r.Rdata")
save(Backtests_HAR_RSRK_e, file = "Data/Backtests_HAR_RSRK_e.Rdata")
save(Backtests_HAR_RSRK_r, file = "Data/Backtests_HAR_RSRK_r.Rdata")
save(Backtests_RGARCH_e, file = "Data/Backtests_RGARCH_e.Rdata")
save(Backtests_RGARCH_r, file = "Data/Backtests_RGARCH_r.Rdata")
save(Backtests_ARMAGARCH_e, file = "Data/Backtests_ARMAGARCH_e.Rdata")
save(Backtests_ARMAGARCH_r, file = "Data/Backtests_ARMAGARCH_r.Rdata")
